### ISSUE TITLE
Launch convex generalized meta strategy to Mainnet

### ISSUE THREAD

**Issue by franckc** [OriginProtocol/origin-dollar#1092]
TODO:
 - [ ] Finish the code review (@DanielVF )
 - [x] CI fork test architecture that simulate various mainnet states (@shahthepro)
 - [ ] ~~Decide which metapools to target (@Techmoen + @sparrowDom)~~
    - ~~Note: Each metapool will have its own strategy contract~~
 - [x] Deploy procedure (@sparrowDom)

**Comment by sparrowDom** [comment]
@DanielVF did you want to do any further review of Generalized Metastrategy Contract code?

**Comment by sparrowDom** [comment]
Closing this for now since I think there are no more actionable items. Feel free to re-open if someone feels there is stuff left to do
