### ISSUE TITLE
Better rebalancing and strategy optimisation methods

### ISSUE THREAD

**Issue by tomlinton** [OriginProtocol/origin-dollar#323]
Right now it is quite tricky to move funds around between strategies. We can improve a lot with:

- More helper methods
- Less reliance on governance for rebalancing

We've discussed this in meetings and I think there is general consensus that we should move toward something like this:

- A store of strategies that have been approved. Approval of a new strategy happens via governance.
- A new role `strategist` that can use methods to rebalance among approved strategies. This might be a non-multisig or a multisig with fewer signers than governance.

To achieve this we need:

- [ ] Support deprecation of a single asset from strategies https://github.com/OriginProtocol/origin-dollar/issues/301
- [x] Integrate liquidation of reward tokens into removeStrategy https://github.com/OriginProtocol/origin-dollar/issues/322
- [x] Addition of an approved strategies array on Vault and associated governable methods to add to it. https://github.com/OriginProtocol/origin-dollar/issues/349
- [x] Implement of the `strategist` address and appropriate modifiers for the methods it can call (e.g. `allocateFrom` described below).
- ~~[ ] A `transferAssets` method to move funds between strategies. It may have arguments like `strategyFromAddr`, `strategyToAddr`, `asset` and `amount`. This could just call `withdraw` on our strategies and pass the `strategyToAddr` as the `_recipient` arg.~~
- [x] A `allocateFrom` method to move funds between Strategies (callable by `strategist`). It's signature would be `(address strategyFromAddr, address strategyToAddr, address[] assets, uint256[] amounts)`. This could just call `withdraw` on a Strategy and pass the `strategyToAddr` as the `_recipient` arg. We would then call the `deposit()` method on the Strategy defined by the `strategyToAddr` argument to allow the recipient Strategy to take whatever actions are necessary to invest the funds. The `deposit()` call probably wouldn't be automatic because we may need to allocate from multiple Strategies into one for things like Uniswap (prior to deposit() being called). 
- [x] Replace the existing allocate/withdraw logic with https://github.com/OriginProtocol/origin-dollar/issues/348

Please add any other methods/functionality that we may require.

This may be important to consider if you are thinking about modifying the strategy abstraction @fxfactorial.

**Comment by DanielVF** [comment]
While there's a lot to do in the whole area of redoing allocations, and adding community governance, and UI's for all, I think it makes sense to start everything off by adding a strategist role and a way to control that role (perhaps a simple 2 of X multisig).

**Comment by DanielVF** [comment]
I think this issue is complete enough? Anything further to do and we can make a new issue?
