### ISSUE TITLE
Governance function audit

### ISSUE THREAD

**Issue by tomlinton** [OriginProtocol/origin-dollar#93]
Putting together a list of everything that is governable. Note everything is subject to timelock with the exception of the deposit pausing.

Currently implemented:

- [x] Address of price provider (`Vault.setPriceProvider`). Subject to change with #90.
- [x] Redeem fee percentage (`Vault.setRedeemFeePercent`).
- [x] Stablecoin asset support (`Vault.supportAsset`).
- [x] Adding of strategy (`Vault.addStrategy`).
- [x] Rebase pausing (`Vault.pauseRebase`, `Vault.unpauseRebase`).
- [x] Deposit pausing (`Vault.pauseDeposits`, `Vault.unpauseDeposits`).
- [x] Liquidate all assets in a strategy back to Vault as part of #74.
- [x] Arbitrary token withdrawal to governor (`Vault.transferToken`, `InitializableAbstractStrategy.transferToken`).

TODOs:

- [ ] Flash loan options pending #91.
